source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
inhibit_all_warnings!

target "FRDemo" do

pod 'AFNetworking', '~> 3.0.0'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'BlocksKit'
pod 'CocoaLumberjack'
pod 'Masonry'
pod 'MJExtension'
pod 'MJRefresh'
pod 'SDWebImage'
pod 'SVProgressHUD'
pod 'TPKeyboardAvoiding'
pod 'MLTransition'
pod 'FMDB'
pod 'CocoaAsyncSocket'
pod 'Shimmer'
pod 'FlatUIKit'
pod 'AsyncDisplayKit'
pod 'RESideMenu'
pod 'SWTableViewCell'
pod 'MWPhotoBrowser'
pod 'WMPageController'

@end