source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

target "FRDemo" do

pod 'AFNetworking', '~> 3.0.0'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'ReactiveCocoa', '~> 4.1.0'
pod 'CocoaLumberjack'
pod 'Masonry'
pod 'MJExtension'
pod 'MJRefresh'
pod 'SDWebImage'
pod 'TPKeyboardAvoiding'
pod 'MLTransition'
pod 'FMDB'
pod 'CocoaAsyncSocket'
pod 'Shimmer'
pod 'AsyncDisplayKit'
pod 'RESideMenu'
pod 'SWTableViewCell'
pod 'MWPhotoBrowser'
pod 'WMPageController'
pod 'FlickerNumber'
pod 'FXBlurView'
pod 'TSMessages'
pod 'RKNotificationHub'

end