source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

target "FRDemo" do

pod 'AFNetworking', '~> 3.0.0'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'ReactiveCocoa', '~> 4.1.0'
pod 'CocoaLumberjack'
pod 'Masonry'
pod 'MJExtension'
pod 'MJRefresh'
pod 'SDWebImage'
pod 'SVProgressHUD'
pod 'TPKeyboardAvoiding'
pod 'MLTransition'
pod 'FMDB'
pod 'CocoaAsyncSocket'
pod 'Shimmer'
pod 'FlatUIKit'
pod 'AsyncDisplayKit'
pod 'RESideMenu'
pod 'SWTableViewCell'
pod 'MWPhotoBrowser'
pod 'WMPageController'

end

/**
Installing AFNetworking (3.0.4)
Installing AsyncDisplayKit (1.9.7)
Installing CocoaAsyncSocket (7.4.3)
Installing CocoaLumberjack (2.2.0)
Installing DACircularProgress (2.3.1)
Installing FMDB (2.6)
Installing FlatUIKit (1.6.2)
Installing MBProgressHUD (0.9.2)
Installing MJExtension (3.0.10)
Installing MJRefresh (3.1.0)
Installing MLTransition (2.0.1)
Installing MWPhotoBrowser (2.1.1)
Installing Masonry (0.6.4)
Installing PINCache (2.2.2)
Installing PINRemoteImage (2.1)
Installing RESideMenu (4.0.7)
Installing ReactiveCocoa (4.1.0)
Installing Result (2.0.0)
Installing SDWebImage (3.7.5)
Installing SVProgressHUD (1.1.3)
Installing SWTableViewCell (0.3.7)
Installing Shimmer (1.0.2)
Installing TPKeyboardAvoiding (1.2.11)
Installing WMPageController (1.4.1)
*/